### ISSUE TITLE
Request a copy of the paper

### ISSUE THREAD

**Issue by yhfnice** [JGManito/gnss_positioning_routines#1]
Dear Manito，Today, I saw the code of your master's thesis on Github. These codes have helped me a lot. Thank you for sharing the results of your labor with us.In order to better understand the content of the code, I would like to obtain a copy of your paper. I hope you can take the time to send me a copy. Thank you very much.Thank you again for sharing. After all, many people are unwilling to share the fruits of their labor with others.Looking forward to your reply.

**Comment by JGManito** [comment]
Hi yhfnice. I have sent you an e-mail with my thesis. Hope it is helpful. 

Best regards
